services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    network_mode: host
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log/nginx:/var/log/nginx
      - php-socket-php:/run/php
      - php-socket-php74:/run/php74
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=2048m

  php:
    image: kjlion/php:fpm-alpine
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html
      -  php-socket-php:/run/php
    depends_on:
      mysql:
        condition: service_healthy


  php74:
    image: kjlion/php:7.4-fpm-alpine
    container_name: php74
    restart: always
    volumes:
      - ./html:/var/www/html
      -  php-socket-php74:/run/php74
    depends_on:
      mysql:
        condition: service_healthy


  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: webroot
      MYSQL_USER: kejilion
      MYSQL_PASSWORD: kejilionYYDS
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pwebroot"]
      interval: 30s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data

volumes:
  php-socket-php:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=64m

  php-socket-php74:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=64m


# networks:
#   default:
#     enable_ipv6: true


